"""add approval relationships

Revision ID: 5e55f5bd6f98
Revises: 4ac554c3ead7
Create Date: 2026-08-22 16:39:59.344339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e55f5bd6f98'
down_revision: Union[str, Sequence[str], None] = '4ac554c3ead7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_approvals_employee_id'), 'approvals', ['employee_id'], unique=False)
    op.create_index(op.f('ix_approvals_transaction_id'), 'approvals', ['transaction_id'], unique=False)
    op.create_foreign_key(None, 'approvals', 'employees', ['employee_id'], ['employee_id'])
    op.create_foreign_key(None, 'approvals', 'transactions', ['transaction_id'], ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_index(op.f('ix_approvals_transaction_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_employee_id'), table_name='approvals')
    # ### end Alembic commands ###
