"""add invoice vendor relationship

Revision ID: 6f7eb485f9b5
Revises: dd0d9dd229cb
Create Date: 2026-08-22 16:31:27.695372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7eb485f9b5'
down_revision: Union[str, Sequence[str], None] = 'dd0d9dd229cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'vendors', ['vendor_id'], ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    # ### end Alembic commands ###
