"""add vendor bank account relationship

Revision ID: dd0d9dd229cb
Revises: e3d57f74cdbd
Create Date: 2026-08-22 16:26:32.831474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0d9dd229cb'
down_revision: Union[str, Sequence[str], None] = 'e3d57f74cdbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vendors_bank_account_id'), 'vendors', ['bank_account_id'], unique=False)
    op.create_foreign_key(None, 'vendors', 'bank_accounts', ['bank_account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_index(op.f('ix_vendors_bank_account_id'), table_name='vendors')
    # ### end Alembic commands ###
